apiVersion: v2
name: todo-app
description: A Helm chart for the Todo Application
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Todo Team
    email: team@todoapp.example.com
keywords:
  - todo
  - application
  - fastapi
  - nextjs
  - postgresql
  - kubernetes
home: https://github.com/hackathon-2-todo/phase2
sources:
  - https://github.com/hackathon-2-todo/phase2