apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: todo-app
data:
  NEXT_PUBLIC_API_BASE_URL: "http://todo-backend.todo-app.svc.cluster.local:8000/api/v1"
  DATABASE_HOST: "todo-postgresql.todo-app.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "todo_app"
  LOG_LEVEL: "INFO"
  DEBUG: "False"